namespace Becometrica.Interop.WinApi.Opengl32;

public enum GlTexturePixelFormat: uint
{
    Alpha = Constants.GL_ALPHA,
    Alpha4 = Constants.GL_ALPHA4,
    Alpha8 = Constants.GL_ALPHA8,
    Alpha12 = Constants.GL_ALPHA12,
    Alpha16 = Constants.GL_ALPHA16,
    Luminance = Constants.GL_LUMINANCE,
    Luminance4 = Constants.GL_LUMINANCE4,
    Luminance8 = Constants.GL_LUMINANCE8,
    Luminance12 = Constants.GL_LUMINANCE12,
    Luminance16 = Constants.GL_LUMINANCE16,
    LuminanceAlpha = Constants.GL_LUMINANCE_ALPHA,
    Luminance4Alpha4 = Constants.GL_LUMINANCE4_ALPHA4,
    Luminance6Alpha2 = Constants.GL_LUMINANCE6_ALPHA2,
    Luminance8Alpha8 = Constants.GL_LUMINANCE8_ALPHA8,
    Luminance12Alpha4 = Constants.GL_LUMINANCE12_ALPHA4,
    Luminance12Alpha12 = Constants.GL_LUMINANCE12_ALPHA12,
    Luminance16Alpha16 = Constants.GL_LUMINANCE16_ALPHA16,
    Intensity = Constants.GL_INTENSITY,
    Intensity4 = Constants.GL_INTENSITY4,
    Intensity8 = Constants.GL_INTENSITY8,
    Intensity12 = Constants.GL_INTENSITY12,
    Intensity16 = Constants.GL_INTENSITY16,
    Rgb = Constants.GL_RGB,
    R3G3B2 = Constants.GL_R3_G3_B2,
    Rgb4 = Constants.GL_RGB4,
    Rgb5 = Constants.GL_RGB5,
    Rgb8 = Constants.GL_RGB8,
    Rgb10 = Constants.GL_RGB10,
    Rgb12 = Constants.GL_RGB12,
    Rgb16 = Constants.GL_RGB16,
    Rgba = Constants.GL_RGBA,
    Rgba2 = Constants.GL_RGBA2,
    Rgba4 = Constants.GL_RGBA4,
    Rgb5A1 = Constants.GL_RGB5_A1,
    Rgba8 = Constants.GL_RGBA8,
    Rgb10A2 = Constants.GL_RGB10_A2,
    Rgba12 = Constants.GL_RGBA12,
    Rgba16 = Constants.GL_RGBA16,
}